name: intergration_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+2
  mockito: ^5.1.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
